# we'll create a deployment, which will run posts application...

apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          imagePullPolicy: Never
          # image: miniapp/posts:0.0.1
          # image: miniapp/posts:0.0.2 # updated from v0.0.1 to v0.0.2
          image: miniapp/posts # by not passing tag i'll make sure it will always pick the latest one

# Now, in order to deploy this deployment
# use command: $ kubectl apply -f posts-deploy.yaml

# creating cluster ip for our post application to communicate
# internally with the other cluster ip services like eventbus etc.
---
apiVersion: v1
kind: Service
metadata:
  name: posts-service-cluster-ip
spec:
#   type: ClusterIP
  selector:
    app: posts
  ports:
  - name: posts
    protocol: TCP
    port: 4000
    targetPort: 4000
